variables:
  LLNL_SERVICE_USER: benchpark-dev

default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lc.llnl.gov/gitlab

include:
  - local: '/.gitlab/ci/test.yml'

stages:
  - status_initiate
  - test
  - status_update
